### ISSUE TITLE
User Story: Landing Page - top reviews

### ISSUE THREAD

**Issue by janimuhlestein** [jlightheart24/over-deliver#1]
As a user, when I navigate to OverDeliver.com, I need to see a list of the top reviews.

Each review must display the following:

1. The name of the restaurant or grocery store.
2. The name of the delivery service.
3. The number of stars given.
4. The customer review attached to the given service/food provider.
5. The number of comments (if any) on the review.
6. The number of up votes on the review.

**Comment by willsan0723** [comment]
Top reviews for past week, or all time? Or perhaps both.

**Comment by janimuhlestein** [comment]
Good question. I'd say start with all time, but, if there got to be a lot of them, switch to just the past week. For student purposes, all time would be best. I'll edit it.

**Comment by jlightheart24** [comment]
Top rated and featured are both functional, working on random service page

**Comment by janimuhlestein** [comment]
Completed.
