### ISSUE TITLE
Create sequelize models in order to create, update, and access the database.

### ISSUE THREAD

**Issue by janimuhlestein** [jlightheart24/over-deliver#3]
Needed models are:

1. User
2. Post
3. Rating
4. Service
5. Provider
6. Comment
7. Vote

**Comment by willsan0723** [comment]
Service will specify if it's grocery delivery or restaurant delivery for now.

**Comment by janimuhlestein** [comment]
Updated as required: removed provider and rating, No images or avatars this time around. Complete.
