### ISSUE TITLE
User Story: Landing Page Header 

### ISSUE THREAD

**Issue by janimuhlestein** [jlightheart24/over-deliver#5]
As a user, I need to be able to filter rating results from the landing page header. 

I need to be able to filter by the following:

1. Service
2. Provider
3. Date
4. Reviewer
5. Rating (asc and desc)
6. Number of Upvotes

**Comment by jlightheart24** [comment]
Header is now functional and the routes between pages work

**Comment by jlightheart24** [comment]
We need to solve the bug where on search page the page shows sign up and log in when logged in instead of log out

**Comment by janimuhlestein** [comment]
Closed.
