### ISSUE TITLE
User Story: Sign Up functionality

### ISSUE THREAD

**Issue by janimuhlestein** [jlightheart24/over-deliver#8]
As a user, I need to be able to sign up for OverDeliver.

1. When I navigate to OverDeliver.com, if I am not logged in, I must see a sign-up link on the header.
2. When I click on the link, then I must be taken to a signup page.
3. This page must contain fields for a username/email, and password.
4. The password must contain at least 6 characters.
5. The username/email must be a viable email.
6. There must be a submit button.
7. When I click on the submit button, the system must verify that I do not already exist as a user.
8. And if I do not, then a new user must be created.
9. If I already exist, the system must inform me of that.
10. If the email address exists, I must be informed of that.
11. After that, I must be returned to the landing page.
12. And there must be a logout link instead of a signup / login link.

**Comment by willsan0723** [comment]
Should we also check that the e-mail isn't already in use as well?

**Comment by janimuhlestein** [comment]
Absolutely.

**Comment by janimuhlestein** [comment]
Completed.
